# Site
title: Caipiratech LAB
subtitle: 

# URL
url: https://caipiratechlab.silo.org.br
baseurl: ''
permalink: :title/
include: ['_pages']

# Build settings
#markdown: kramdown
#port: 4666
#future: false

# Plugins
repository: associacaosilo/caipiratech
plugins:
  - jekyll-feed

# Collections (Custom Posts)
collections:
  - foruns
  - cursos