# Site
title: MapaCozinhas
subtitle: 

# URL
url: https://mapa-cozinhas.github.io
baseurl: ''
permalink: :title/
include: ['_pages']

# Build settings
#markdown: kramdown
#port: 4666
#future: false

# Plugins
repository: institutoasw/mapa-cozinhas
#plugins:
  #- jekyll-feed

# Collections (Custom Posts)
collections:
  - boletins
  - cursos
  
# Data (twitter_user não utilizado no momento. Descomentar quando tiver o "_includes/meta.html")
  # "social:" foi movido para _data/social.yml. Utilizar variável "site.data.social" em vez de "site.social"
# twitter_user: "SiloLatitude"

# prose.io
prose:
  media: 'media/images'
  ignore:
    - .gitignore
    - _config.yml
    - _data
    - _includes
    - _layouts
    - _sass
    - css
    - js
    - CNAME
    - TODO.md
    - publish.sh
    - media/favicons
    - media/swipebox

  metadata:
    _boletins:
      - name: "published"
        field:
          element: "hidden"
          value: "true"
      - name: "titulo"
        field:
          element: "text"
          label: "Título do Grupo de boletins"
          placeholder: "Colocar aqui o nome do assunto que gerou os boletins"
      - name: "ordem"
        field:
          element: "number"
          label: "Ordem para aparecer"
          placeholder: "Colocar Aqui um número para criar uma ordem dos assuntos dos boletins"
          help: "Quanto menor o número, mais acima ele aparece"  
      - name: "descricao"
        field:
          element: "textarea"
          label: "Descrição do Assunto dos boletins"
          placeholder: "Escreva aqui a descrição deste grupo de boletins"
    _cursos:
      - name: "published"
        field:
          element: "hidden"
          value: "true"
      - name: "titulo"
        field:
          element: "text"
          label: "Nome do Módulo"
          placeholder: "MÓDULO X – Nome do Módulo"
      - name: "ordem"
        field:
          element: "number"
          label: "Ordem para aparecer"
          placeholder: "Colocar Aqui um número para criar uma ordem dos cursos"
          help: "Quanto menor o número, mais acima ele aparece"     