# Site
title: CaipiratechLAB
subtitle: 

# URL
url: https://caipiratechlab.silo.org.br
baseurl: ''
permalink: :title/
include: ['_pages']

# Build settings
#markdown: kramdown
#port: 4666
#future: false

# Plugins
repository: associacaosilo/caipiratech
plugins:
  - jekyll-feed

# Collections (Custom Posts)
collections:
  - foruns
  - cursos
  
# prose.io
prose:
  media: 'media/images'
  ignore:
    - .gitignore
    - _config.yml
    - _data
    - _includes
    - _layouts
    - _sass
    - css
    - js
    - CNAME
    - TODO.md
    - publish.sh
    - media/favicons
    - media/swipebox

  metadata:
    _foruns:
      - name: "published"
        field:
          element: "hidden"
          value: "true"
      - name: "titulo"
        field:
          element: "text"
          label: "Título do Fórum"
          placeholder: "Colocar Aqui o Nome do Fórum"
      - name: "ordem"
        field:
          element: "number"
          label: "Ordem para aparecer"
          placeholder: "Colocar Aqui um número para criar uma ordem dos fóruns"
          help: "Quanto menor o número, mais acima ele aparece"  
      - name: "descricao"
        field:
          element: "textarea"
          label: "Descrição do Fórum"
          placeholder: "Escreva aqui a descrição deste fórum"
    _cursos:
      - name: "published"
        field:
          element: "hidden"
          value: "true"
      - name: "titulo"
        field:
          element: "text"
          label: "Nome do Módulo"
          placeholder: "MÓDULO X – Nome do Módulo"
      - name: "ordem"
        field:
          element: "number"
          label: "Ordem para aparecer"
          placeholder: "Colocar Aqui um número para criar uma ordem dos cursos"
          help: "Quanto menor o número, mais acima ele aparece"     